# Generated by Django 3.0.7 on 2020-06-19 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_auto_20200619_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_role',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.Agents'),
        ),
        migrations.AlterField(
            model_name='agent_role',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.Roles'),
        ),
        migrations.AlterField(
            model_name='agents',
            name='available_since',
            field=models.DateTimeField(),
        ),
    ]
