# Generated by Django 3.0.7 on 2020-06-23 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_auto_20200623_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_role',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.Agents'),
        ),
        migrations.AlterField(
            model_name='agent_role',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.Roles'),
        ),
    ]
