# Generated by Django 3.0.7 on 2020-06-24 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_auto_20200623_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent_role',
            options={'verbose_name_plural': 'Agent_role'},
        ),
        migrations.AlterModelOptions(
            name='agents',
            options={'verbose_name_plural': 'Agents'},
        ),
        migrations.AlterModelOptions(
            name='issues',
            options={'verbose_name_plural': 'Issues'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterField(
            model_name='agent_role',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.Agents'),
        ),
        migrations.AlterField(
            model_name='agent_role',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.Roles'),
        ),
        migrations.CreateModel(
            name='Issue_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.Issues')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.Roles')),
            ],
            options={
                'verbose_name_plural': 'Issue_role',
            },
        ),
    ]
