# Generated by Django 3.0.7 on 2020-06-24 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_auto_20200624_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='no_roles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issues',
            name='no_roles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent_role',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.Agents'),
        ),
        migrations.AlterField(
            model_name='agent_role',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.Roles'),
        ),
        migrations.AlterField(
            model_name='issue_role',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.Roles'),
        ),
    ]
